version: '3.1'

services:
  postgres-ttl:
    image: "postgres:14.4-alpine"
    container_name: postgres-ttl
    ports:
      - "5432:5432"
    volumes:
      - "postgres-ttl:/var/lib/postgresql/data"
      - "./postgresql.conf:/etc/postgresql/postgresql.conf"
    environment:
      - POSTGRES_USER=TTL_USER_DB
      - POSTGRES_PASSWORD=WeLoveToLearn
      - POSTGRES_DB=Talenta
volumes:
  postgres-ttl:
    driver: local